import { useCallback, useEffect, useState } from 'react';
import { Activity, Briefcase, CheckCircle2, Clock3, RefreshCw, Send, ShieldCheck, Users } from 'lucide-react';
import toast from 'react-hot-toast';
import { adminDashboardService } from '../services/admin-dashboard.service';

type DashboardData = Awaited<ReturnType<typeof adminDashboardService.getResumen>>;
const formatNumber = (value: number) => new Intl.NumberFormat('es-CO').format(value);

const DonutChart = ({ candidates, companies }: { candidates: number; companies: number }) => {
  const total = candidates + companies;
  const percentage = total ? Math.round((candidates / total) * 100) : 0;
  const circumference = 2 * Math.PI * 42;
  return <div className="relative h-44 w-44 shrink-0"><svg viewBox="0 0 100 100" className="h-full w-full -rotate-90"><circle cx="50" cy="50" r="42" fill="none" stroke="#e2e8f0" strokeWidth="12" /><circle cx="50" cy="50" r="42" fill="none" stroke="#3b82f6" strokeWidth="12" strokeDasharray={`${circumference * (percentage / 100)} ${circumference}`} strokeLinecap="round" /></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><b className="text-3xl text-slate-900">{percentage}%</b><span className="text-xs text-slate-500">candidatos</span></div></div>;
};

const StatusBars = ({ items }: { items: { label: string; value: number; color: string }[] }) => {
  const max = Math.max(...items.map(item => item.value), 1);
  return <div className="space-y-3">{items.map(item => <div key={item.label}><div className="mb-1 flex justify-between text-xs"><span className="text-slate-600">{item.label}</span><b className="text-slate-800">{formatNumber(item.value)}</b></div><div className="h-2 rounded-full bg-slate-100"><div className={`h-2 rounded-full ${item.color} transition-all duration-500`} style={{ width: `${(item.value / max) * 100}%` }} /></div></div>)}</div>;
};

const Metric = ({ label, value, icon: Icon, color }: { label: string; value: number; icon: typeof Users; color: string }) => (
  <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm font-medium text-slate-500">{label}</p><div className={`rounded-xl p-3 ${color}`}><Icon className="h-5 w-5" /></div></div><p className="mt-4 text-3xl font-extrabold text-slate-900">{formatNumber(value)}</p></div>
);

export const AdminDashboardView = () => {
  const [data, setData] = useState<DashboardData | null>(null);
  const [loading, setLoading] = useState(true);
  const [lastUpdated, setLastUpdated] = useState<Date | null>(null);
  const load = useCallback(async () => { setLoading(true); try { setData(await adminDashboardService.getResumen()); setLastUpdated(new Date()); } catch { toast.error('No se pudo cargar el resumen del sistema'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); const interval = window.setInterval(() => void load(), 30000); return () => window.clearInterval(interval); }, [load]);
  if (loading && !data) return <div className="flex min-h-96 items-center justify-center text-slate-500"><RefreshCw className="mr-2 h-5 w-5 animate-spin" />Cargando datos reales...</div>;

  const usuarios = data?.usuarios; const ofertas = data?.ofertas; const postulaciones = data?.postulaciones; const total = usuarios?.totalUsuarios ?? 0;
  const candidatosPercent = total ? Math.round((usuarios!.candidatos / total) * 100) : 0;
  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-extrabold text-slate-900">Dashboard administrativo</h1><p className="text-sm text-slate-500">Resumen en tiempo real de la plataforma.</p></div><button onClick={() => void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 shadow-sm hover:bg-slate-50 disabled:opacity-60"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Actualizar</button></div>
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Usuarios registrados" value={total} icon={Users} color="bg-blue-50 text-blue-600" /><Metric label="Ofertas publicadas" value={ofertas?.ofertasPublicadas ?? 0} icon={Briefcase} color="bg-violet-50 text-violet-600" /><Metric label="Postulaciones" value={postulaciones?.totalPostulaciones ?? 0} icon={Send} color="bg-emerald-50 text-emerald-600" /><Metric label="Pendientes de atención" value={(usuarios?.usuariosPendientes ?? 0) + (ofertas?.ofertasPendientes ?? 0) + (postulaciones?.enRevision ?? 0)} icon={Clock3} color="bg-amber-50 text-amber-600" /></div>
    <div className="grid grid-cols-1 gap-6 lg:grid-cols-3"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2"><div className="mb-6 flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Actividad del sistema</h2><p className="text-sm text-slate-500">Distribución actual de usuarios y operaciones.</p></div><Activity className="h-5 w-5 text-indigo-500" /></div><div className="grid gap-5 sm:grid-cols-2"><div><div className="mb-2 flex justify-between text-sm"><span className="text-slate-600">Candidatos</span><b>{formatNumber(usuarios?.candidatos ?? 0)} ({candidatosPercent}%)</b></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-blue-500 transition-all" style={{ width: `${candidatosPercent}%` }} /></div></div><div><div className="mb-2 flex justify-between text-sm"><span className="text-slate-600">Empresas</span><b>{formatNumber(usuarios?.empresas ?? 0)}</b></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-violet-500 transition-all" style={{ width: `${total ? Math.round((usuarios!.empresas / total) * 100) : 0}%` }} /></div></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Ofertas pendientes</p><p className="mt-1 text-2xl font-bold text-amber-600">{formatNumber(ofertas?.ofertasPendientes ?? 0)}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Entrevistas registradas</p><p className="mt-1 text-2xl font-bold text-indigo-600">{formatNumber(postulaciones?.totalEntrevistas ?? 0)}</p></div></div></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold text-slate-900">Servicios conectados</h2><p className="mb-5 text-sm text-slate-500">Última consulta: {lastUpdated?.toLocaleTimeString('es-CO') ?? '—'}</p><div className="space-y-3">{['Usuarios', 'Ofertas', 'Postulaciones'].map(service => <div key={service} className="flex items-center justify-between rounded-xl bg-emerald-50 px-4 py-3"><span className="font-medium text-slate-700">Servicio de {service}</span><span className="inline-flex items-center gap-1 text-xs font-bold text-emerald-700"><CheckCircle2 className="h-4 w-4" />Activo</span></div>)}</div><div className="mt-5 flex items-center gap-2 text-xs text-slate-500"><ShieldCheck className="h-4 w-4 text-emerald-600" />Datos consultados desde los microservicios</div></section></div>
    <div className="grid grid-cols-1 gap-6 xl:grid-cols-3"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-1 font-bold text-slate-900">Distribución de usuarios</h2><p className="mb-5 text-sm text-slate-500">Candidatos frente a empresas.</p><div className="flex items-center justify-center gap-6"><DonutChart candidates={usuarios?.candidatos ?? 0} companies={usuarios?.empresas ?? 0} /><div className="space-y-3 text-sm"><p><span className="mr-2 inline-block h-3 w-3 rounded-full bg-blue-500" />Candidatos: <b>{formatNumber(usuarios?.candidatos ?? 0)}</b></p><p><span className="mr-2 inline-block h-3 w-3 rounded-full bg-slate-200" />Empresas: <b>{formatNumber(usuarios?.empresas ?? 0)}</b></p><p className="border-t pt-3 text-slate-500">Activos: <b className="text-emerald-600">{formatNumber(usuarios?.usuariosActivos ?? 0)}</b></p></div></div></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-1 font-bold text-slate-900">Estado de ofertas</h2><p className="mb-5 text-sm text-slate-500">Ofertas en cada etapa.</p><StatusBars items={[{ label: 'Publicadas', value: ofertas?.ofertasPublicadas ?? 0, color: 'bg-emerald-500' }, { label: 'Pendientes', value: ofertas?.ofertasPendientes ?? 0, color: 'bg-amber-500' }, { label: 'Borradores', value: ofertas?.ofertasBorrador ?? 0, color: 'bg-slate-400' }, { label: 'Rechazadas', value: ofertas?.ofertasRechazadas ?? 0, color: 'bg-rose-500' }, { label: 'Cerradas', value: ofertas?.ofertasCerradas ?? 0, color: 'bg-indigo-500' }]} /></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-1 font-bold text-slate-900">Estado de postulaciones</h2><p className="mb-5 text-sm text-slate-500">Seguimiento del proceso.</p><StatusBars items={[{ label: 'Enviadas', value: postulaciones?.enviadas ?? 0, color: 'bg-blue-500' }, { label: 'En revisión', value: postulaciones?.enRevision ?? 0, color: 'bg-amber-500' }, { label: 'Preseleccionadas', value: postulaciones?.preseleccionadas ?? 0, color: 'bg-violet-500' }, { label: 'Entrevistas', value: postulaciones?.entrevistas ?? 0, color: 'bg-indigo-500' }, { label: 'Seleccionadas', value: postulaciones?.seleccionadas ?? 0, color: 'bg-emerald-500' }, { label: 'Rechazadas', value: postulaciones?.rechazadas ?? 0, color: 'bg-rose-500' }]} /></section></div>
  </div>;
};
