spring.application.name=usuarios-service

server.port=8081

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/db_empleabilidad?currentSchema=schema_usuarios
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=schema_usuarios
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true

# JWT Secret
jwt.secret=my-super-secret-key-that-should-be-changed-in-production

storage.local.base-path=${STORAGE_LOCAL_BASE_PATH:${java.io.tmpdir}}
storage.cv.max-size-mb=${STORAGE_CV_MAX_SIZE_MB:5}

# APIsPERU - Configuracion para consultas DNI/RUC
apisperu.token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imxlb2NyaXNwYWl0YW5AZ21haWwuY29tIn0.B1FXdA8jdiP7gi30QMYfKvRXq0WjWCTHA5i1fzlukug
apisperu.auth-url=https://facturacion.apisperu.com/api/v1/auth/login
apisperu.dni-url=https://dniruc.apisperu.com/api/v1/dni
apisperu.ruc-url=https://dniruc.apisperu.com/api/v1/ruc
apisperu.username=Botsito1
apisperu.password=Contreras30
