import { api, ofertasPublicApi, postulacionesApi } from '@/core/api';
import type { PageResponse } from '@/shared/types';
import type { AdminPostulacion, EstadoPostulacion } from '../views/AdminPostulacionesView';

interface ApiPostulacion { uuid: string; candidatoId: string; ofertaId: string; empresaId: string; fechaPostulacion: string; fechaActualizacion?: string; estado: string; porcentajeCoincidencia?: number; cvAdjunto: boolean; entrevistaFecha?: string; }
interface ApiUsuario { id: string; uuid: string; nombreCompleto: string; email: string; }
interface ApiOferta { id: string; titulo: string; empresaId: string; modalidad?: 'REMOTO' | 'HIBRIDO' | 'PRESENCIAL'; ubicacion?: string; }
const stateMap: Record<string, EstadoPostulacion> = { ENVIADA: 'PENDIENTE', RECIBIDA: 'PENDIENTE', EN_REVISION: 'EN_REVISION', PRESELECCIONADA: 'PRESELECCIONADO', ENTREVISTA: 'ENTREVISTA_PROGRAMADA', EVALUACION: 'EN_REVISION', SELECCIONADA: 'ACEPTADO', RECHAZADA: 'RECHAZADO', RETIRADA: 'RETIRADO', CANCELADA: 'RECHAZADO', CERRADA: 'RECHAZADO' };
const map = (p: ApiPostulacion, users: Map<string, ApiUsuario>, jobs: Map<string, ApiOferta>): AdminPostulacion => { const candidate = users.get(p.candidatoId); const job = jobs.get(p.ofertaId); const company = users.get(p.empresaId); return { id: p.uuid, candidatoNombre: candidate?.nombreCompleto || 'Candidato', candidatoEmail: candidate?.email || '—', candidatoCarrera: '—', candidatoUniversidad: '—', candidatoCiclo: '—', ofertaTitulo: job?.titulo || 'Oferta aplicada', ofertaEmpresa: company?.nombreCompleto || 'Empresa', ofertaModalidad: job?.modalidad || 'REMOTO', ofertaUbicacion: job?.ubicacion || '—', estado: stateMap[p.estado] ?? 'PENDIENTE', fechaPostulacion: p.fechaPostulacion, fechaActualizacion: p.fechaActualizacion ?? p.fechaPostulacion, matchScore: p.porcentajeCoincidencia ?? 0, cvAdjunto: p.cvAdjunto, entrevistaFecha: p.entrevistaFecha }; };
export const adminPostulacionesService = { listar: async (params = {}) => { const [{ data }, usersResponse, jobsResponse] = await Promise.all([postulacionesApi.get<PageResponse<ApiPostulacion>>('/admin/postulaciones', { params: { size: 100, ...params } }), api.get<PageResponse<ApiUsuario>>('/admin/usuarios', { params: { size: 500 } }), ofertasPublicApi.get<PageResponse<ApiOferta>>('/ofertas', { params: { size: 500 } })]); const users = new Map((usersResponse.data.content ?? []).flatMap(user => [[user.id, user], [user.uuid, user]])); const jobs = new Map((jobsResponse.data.content ?? []).map(job => [job.id, job])); return { ...data, content: (data.content ?? []).map(item => map(item, users, jobs)) }; }, cambiarEstado: async (id: string, estado: string) => postulacionesApi.put(`/admin/postulaciones/${id}/estado`, null, { params: { estado } }) };
