spring.application.name=ofertas-service
server.port=8082

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/db_empleabilidad?currentSchema=schema_ofertas
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA y Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret
jwt.secret=my-super-secret-key-that-should-be-changed-in-production

# Seguridad JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/empleabilidad

# OpenAPI / Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs